networks:
  apps_local:
    external: true

volumes:
  db-volume:

services:
  webserver:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:latest
    ports:
      - "8090:80"
    networks:
      - default
      - apps_local
    depends_on:
      - app
    volumes:
      - ./app:/var/www/app
      - ./services/nginx/conf.d/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      APP_CONTAINER: ${PROJECT_NAME}-app

  app:
    &php-app
    image: brian978/php-fpm:8.4-dev
    container_name: ${PROJECT_NAME}-app
    working_dir: /var/www/app
    networks:
      - default
      - apps_local
    volumes:
      - ./app:/var/www/app:cached
      - ./services/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./services/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./logs/php:/var/log/php
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  db:
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    image: mysql:8.4.7
    ports:
      - "33061:3306"
    networks:
      - default
      - apps_local
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}_app
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345

  scheduler:
    <<: *php-app
    container_name: ${PROJECT_NAME}-scheduler
    command: php artisan schedule:work

  worker:
    <<: *php-app
    container_name: ${PROJECT_NAME}-worker
    restart: unless-stopped
    command: php artisan queue:listen

  vite:
    <<: *php-app
    container_name: ${PROJECT_NAME}-vite
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www/app